inputs:
  keychain-name:
    description: "Name of the keychain to install provisioning profile into"
    required: true
  provisioning-profile-base64:
    description: "Base64 encoded provisioning profile (.mobileprovision)"
    required: true
  profile-name:
    description: "Name for the provisioning profile (for logging)"
    required: false
    default: "provisioning profile"

runs:
  using: "composite"
  steps:
    - name: Install provisioning profile
      shell: bash
      run: |
        echo "Installing ${{ inputs.profile-name }} into keychain: ${{ inputs.keychain-name }}"

        # Decode and install provisioning profile
        echo "${{ inputs.provisioning-profile-base64 }}" | base64 --decode > profile.mobileprovision

        # Copy to provisioning profiles directory
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

        # Clean up temporary file
        rm -f profile.mobileprovision

        echo "${{ inputs.profile-name }} installed successfully"
