name: "Setup iOS Build Environment"
description: "Setup keychain, certificates, Xcode, and API keys for iOS builds"

inputs:
  keychain-password:
    description: "Password for the keychain"
    required: true
  certificate-base64:
    description: "Base64 encoded distribution certificate"
    required: true
  certificate-password:
    description: "Password for the distribution certificate"
    required: true
  app-store-connect-api-key:
    description: "App Store Connect API Key content"
    required: true
  app-store-connect-api-key-id:
    description: "App Store Connect API Key ID"
    required: true
  xcode-version:
    description: "Xcode version to use"
    required: true
  environment-name:
    description: "Environment name for keychain naming (test, dev, staging, prod)"
    required: true

outputs:
  keychain-name:
    description: "Name of the created keychain"
    value: ${{ steps.keychain.outputs.keychain-name }}

runs:
  using: "composite"
  steps:
    - name: Create keychain
      id: keychain
      shell: bash
      run: |
        KEYCHAIN_NAME="build-${{ inputs.environment-name }}-${{ github.run_id }}.keychain"
        echo "keychain-name=$KEYCHAIN_NAME" >> $GITHUB_OUTPUT

        echo "Creating temporary keychain: $KEYCHAIN_NAME"
        security create-keychain -p "${{ inputs.keychain-password }}" "$KEYCHAIN_NAME"
        security set-keychain-settings -lut 21600 "$KEYCHAIN_NAME"
        security default-keychain -s "$KEYCHAIN_NAME"
        security unlock-keychain -p "${{ inputs.keychain-password }}" "$KEYCHAIN_NAME"

    - name: Setup iOS certificates
      uses: ./.github/actions/setup-ios-certificates
      with:
        keychain-name: ${{ steps.keychain.outputs.keychain-name }}
        keychain-password: ${{ inputs.keychain-password }}
        certificate-base64: ${{ inputs.certificate-base64 }}
        certificate-password: ${{ inputs.certificate-password }}

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ inputs.xcode-version }}

    - name: Setup App Store Connect API key
      shell: bash
      run: |
        # Create the API key file in the expected location
        mkdir -p ${{ env.API_PRIVATE_KEYS_DIR }}
        echo "${{ inputs.app-store-connect-api-key }}" > ${{ env.API_PRIVATE_KEYS_DIR }}/AuthKey_${{ inputs.app-store-connect-api-key-id }}.p8
