name: "Cleanup iOS Build Environment"
description: "Clean up keychain and provisioning profiles"

inputs:
  keychain-name:
    description: "Name of the keychain to clean up"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cleanup
      if: always()
      shell: bash
      run: |
        # Clean up keychain
        security delete-keychain "${{ inputs.keychain-name }}" 2>/dev/null || true
        security default-keychain -s login.keychain

        # Clean up provisioning profiles from both possible locations
        rm -rf ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision 2>/dev/null || true
        rm -rf ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles/*.mobileprovision 2>/dev/null || true
